# Generated by Django 2.0.6 on 2018-08-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('count', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='update',
            field=models.DateTimeField(),
        ),
    ]
