# Generated by Django 2.0.6 on 2018-07-15 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('update', models.TimeField()),
                ('logo', models.ImageField(upload_to='')),
                ('url', models.URLField()),
                ('lock', models.BooleanField(default=True)),
                ('intro', models.CharField(max_length=500)),
                ('privacy', models.CharField(max_length=50)),
                ('doPrivacy', models.CharField(max_length=50)),
                ('uName', models.CharField(max_length=50)),
                ('uTell', models.IntegerField()),
                ('uUrl', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('replyCount', models.IntegerField()),
                ('replyTime', models.DateTimeField()),
                ('createTime', models.DateTimeField()),
                ('updateTime', models.DateTimeField()),
                ('clicks', models.IntegerField()),
                ('upCount', models.IntegerField()),
                ('status', models.BooleanField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('title', models.CharField(max_length=10)),
                ('sectionId', models.IntegerField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('userId', models.IntegerField(primary_key=True, serialize=False)),
                ('regTime', models.DateTimeField()),
                ('name', models.CharField(max_length=10)),
                ('sex', models.NullBooleanField()),
                ('birth', models.DateTimeField(default='1000-01-01')),
                ('url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='count.Writer'),
        ),
        migrations.AddField(
            model_name='article',
            name='section_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='count.Section'),
        ),
    ]
